/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RiskIndexRouteImport } from './routes/risk.index'
import { Route as RiskDiabetesRouteImport } from './routes/risk.diabetes'
import { Route as RiskHeartRouteImport } from './routes/risk.heart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIndexRoute = RiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDiabetesRoute = RiskDiabetesRouteImport.update({
  id: '/risk/diabetes',
  path: '/risk/diabetes',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskHeartRoute = RiskHeartRouteImport.update({
  id: '/risk/heart',
  path: '/risk/heart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/risk/diabetes': typeof RiskDiabetesRoute
  '/risk/heart': typeof RiskHeartRoute
  '/risk/': typeof RiskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/risk/diabetes': typeof RiskDiabetesRoute
  '/risk/heart': typeof RiskHeartRoute
  '/risk': typeof RiskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/risk/diabetes': typeof RiskDiabetesRoute
  '/risk/heart': typeof RiskHeartRoute
  '/risk/': typeof RiskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/risk/diabetes'
    | '/risk/heart'
    | '/risk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/risk/diabetes'
    | '/risk/heart'
    | '/risk'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/risk/diabetes'
    | '/risk/heart'
    | '/risk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  RiskDiabetesRoute: typeof RiskDiabetesRoute
  RiskHeartRoute: typeof RiskHeartRoute
  RiskIndexRoute: typeof RiskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/': {
      id: '/risk/'
      path: '/risk'
      fullPath: '/risk/'
      preLoaderRoute: typeof RiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/diabetes': {
      id: '/risk/diabetes'
      path: '/risk/diabetes'
      fullPath: '/risk/diabetes'
      preLoaderRoute: typeof RiskDiabetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/heart': {
      id: '/risk/heart'
      path: '/risk/heart'
      fullPath: '/risk/heart'
      preLoaderRoute: typeof RiskHeartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  RiskDiabetesRoute: RiskDiabetesRoute,
  RiskHeartRoute: RiskHeartRoute,
  RiskIndexRoute: RiskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
